"token"="" # the bot's token
"prefix"="t^" # prefix used to denote commands
"spotifyClientId"=""
"spotifyClientSecret"=""
"deezerARL"=""
[music]
# Options for the music commands
"max_volume"=250 # Max audio volume. Set to -1 for unlimited.
"vote_skip"=false # whether vote-skipping is enabled
"vote_skip_ratio"=0.5 # the minimum ratio of votes needed to skip a song
[tips]
"github_url"="https://github.com/thikkachu/thikkBot"

